### ISSUE TITLE
Update importing section in doc

### ISSUE THREAD

**Issue by Morerice** [const-se/selectize-bootstrap4-theme#5]
![selection_008](https://user-images.githubusercontent.com/11156828/45928385-f0976300-bf42-11e8-8b56-f6bc3d677a31.jpg)

There is a very small issue with the importing file mentioned in the importing section.
The only small update required is to change `selectise.bootstrap4` to `selectize.bootstrap4`

**Comment by olssonm** [comment]
Discovered this one too the other day, made a PR https://github.com/const-se/selectize-bootstrap4-theme/pull/6

**Comment by const-se** [comment]
PR #6 was merged.
